server: 
    port: 6677
spring:
    application:
        name: eureka-micro-gateway
#网关
zuul:
  routes:
    goods-serice: #自定义的
        path: /goods-service/** #url请求规则
        #url: http://localhost:8081 #真正的地址
        serviceId: eureka-micro-goods
        
eureka: 
    client:
        #向注册中心注册自己
        registerWithEureka: true
        #检索服务 这里是注册中心
        fetchRegistry: true
        #客户端与服务端地址
        serviceUrl:
            defaultZone: http://singleton:singleton@localhost:6868/eureka/
    instance: 
       prefer-ip-address: true #将自己的IP注册到服务中心去