server: 
    port: 8082
spring:
    application:
        name: eureka-micro-order
eureka: 
    client:
        #向注册中心注册自己
        registerWithEureka: false
        #检索服务 获取注册信息
        fetchRegistry: true
        #客户端与服务端地址
        serviceUrl:
            defaultZone: http://singleton:singleton@localhost:6868/eureka/
    instance: 
       prefer-ip-address: true #将自己的IP注册到服务中心去

#随机请求 负载均衡       
eureka-micro-goods: 
    ribbon: 
        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule