server:
    #tomcat:
     #   uri-encoding: UTF-8
      #  max-threads: 1000
       # min-spare-threads: 30
    port: 1111
spring:
    application:
        name: eureka-server
        
management:
    contextPath: /hello
endpoints:
    info:
        path: /appinfo
    health:
        path: /checkHealth
eureka:
    instance:
        statusPageUrlPath: ${management.contextPath}/${endpoints.info.path}
        healthCheckUrlPath: ${management.contextPath}/${endpoints.health.path}
    client:
        #不向注册中心注册自己
        registerWithEureka: false
        #检索服务 这里是注册中心
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/